# Generated by Django 3.1.7 on 2021-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=254, verbose_name='اسم المنتج')),
                ('qty', models.PositiveSmallIntegerField(verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('notes', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
