# Generated by Django 3.1.7 on 2021-03-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210305_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
