# Generated by Django 4.0.5 on 2022-06-12 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_card_alter_purchase_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item_card', verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item_card', verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item_card', verbose_name='اسم المنتج'),
        ),
    ]
