# Generated by Django 4.1.3 on 2022-12-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_inventory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tool', models.CharField(max_length=100)),
                ('mac_tool', models.CharField(max_length=100)),
                ('ip_tool', models.CharField(max_length=100)),
                ('ssid_tool', models.CharField(max_length=100)),
                ('model_tool', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Towers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tower', models.CharField(max_length=100)),
                ('location_tower', models.CharField(max_length=100)),
            ],
        ),
    ]
