# Generated by Django 4.1.3 on 2022-12-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_towersandtools_tools_inventory_tool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towersandtools',
            name='id_tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.tools'),
        ),
    ]
