# Generated by Django 4.1.3 on 2022-12-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_towersandtools_id_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersAndTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_customer', models.IntegerField()),
                ('id_tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.tools')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(max_length=100)),
                ('tools_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.towersandtools')),
            ],
        ),
    ]
