# Generated by Django 4.1.3 on 2022-12-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_customersandtools_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='tools_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.tools'),
        ),
        migrations.AlterField(
            model_name='customersandtools',
            name='id_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.customers'),
        ),
        migrations.AlterField(
            model_name='towers',
            name='tools_tower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.tools'),
        ),
        migrations.AlterField(
            model_name='towersandtools',
            name='id_towers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.towers'),
        ),
    ]
