# Generated by Django 4.1.3 on 2022-12-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_alter_customers_tools_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towers',
            name='tools_tower',
        ),
        migrations.AddField(
            model_name='towers',
            name='tools_tower',
            field=models.ManyToManyField(to='sections.tools'),
        ),
    ]
