# Generated by Django 4.1.3 on 2022-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_remove_towersandtools_id_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='towers',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
