# Generated by Django 4.1.3 on 2022-12-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0010_alter_tools_ip_tool_alter_tools_mac_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
