# Generated by Django 3.1.7 on 2022-12-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0013_auto_20221222_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towers',
            name='tools_tower',
        ),
        migrations.AddField(
            model_name='tools',
            name='tower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sections.towers'),
            preserve_default=False,
        ),
    ]
